# Advanced Applied Math II (Intensive course in Kobe Univ., Aug. 2021)
### Instructor: Xiao-Nan Lu (Univ. Yamanashi)

# Day 2: Hadamard Matrices & BIB Designs

## Example: Hadamard matrix of dimension $2$

In [1]:
import numpy as np

H2 = np.array([ [1, 1],  [1, -1] ])
print("H2 = \n", H2) 
print("\n H2^T H2 = \n", np.matmul(H2.transpose(), H2))

H2 = 
 [[ 1  1]
 [ 1 -1]]

 H2^T H2 = 
 [[2 0]
 [0 2]]


## Example: Kronecker product of Hadamard matrices of dimension $2^m$

In [2]:
m = 3

H = H2 # start from 2-dimensional Hadamard matrix
for i in range(m-1):
    H = np.kron(H, H2) # Kronecker product of H and H2 
    
print("This is an Hadamard matrix of dimension %d \n" % 2**m, H)
print("\n H^T H = \n", np.matmul(H.transpose(), H))

This is an Hadamard matrix of dimension 8 
 [[ 1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1]]

 H^T H = 
 [[8 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0]
 [0 0 0 8 0 0 0 0]
 [0 0 0 0 8 0 0 0]
 [0 0 0 0 0 8 0 0]
 [0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 8]]


## Example: Legendre symbol 

In [3]:
def Legendre(a, p):
    a = a % p
    if a == 0:
        return 0
    if a in [i*i % p for i in range(1, (p+1)//2) ]:
        return 1
    else:
        return -1;

p = 7
print([ Legendre(a, p) for a in range(p)])

for i in range(1, p):
    print("%d^2 = %d mod %d" % (i, i*i % p, p))
    

[0, 1, 1, -1, 1, -1, -1]
1^2 = 1 mod 7
2^2 = 4 mod 7
3^2 = 2 mod 7
4^2 = 2 mod 7
5^2 = 4 mod 7
6^2 = 1 mod 7


## Example: spring balance weighing design

In [4]:
def inform_mat(d):
    return np.dot(np.transpose(d), d);

In [5]:
from scipy.linalg import circulant

d = circulant([1, 0, 0, 0, 1, 0, 1])
print("D2= \n", d)

m = inform_mat(d)
print("\n D2^T * D2= \n", m)

D2= 
 [[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [0 0 1 1 0 1 0]
 [0 0 0 1 1 0 1]
 [1 0 0 0 1 1 0]
 [0 1 0 0 0 1 1]
 [1 0 1 0 0 0 1]]

 D2^T * D2= 
 [[3 1 1 1 1 1 1]
 [1 3 1 1 1 1 1]
 [1 1 3 1 1 1 1]
 [1 1 1 3 1 1 1]
 [1 1 1 1 3 1 1]
 [1 1 1 1 1 3 1]
 [1 1 1 1 1 1 3]]


In [6]:
inv_m = np.linalg.inv(m)
estimate_m = np.dot(inv_m, np.transpose(d))
print(6*estimate_m)

[[ 2. -1. -1. -1.  2. -1.  2.]
 [ 2.  2. -1. -1. -1.  2. -1.]
 [-1.  2.  2. -1. -1. -1.  2.]
 [ 2. -1.  2.  2. -1. -1. -1.]
 [-1.  2. -1.  2.  2. -1. -1.]
 [-1. -1.  2. -1.  2.  2. -1.]
 [-1. -1. -1.  2. -1.  2.  2.]]


## Example: check whether $(v, k, \lambda)$ is admissible parameter for BIBD

In [7]:
def is_admissible_BIBD(v, k, lamb):
    # use r*(k-1) = lamb * (v-1)
    r_res = lamb * (v-1) % (k-1)
    if r_res > 0:
        print("r = %d/%d is not an integer!" % ( lamb * (v-1), k-1))
        return False
    else:
        # use v*r = b*k
        r = lamb * (v-1) // (k-1)
        b_res = v * r % k
        if b_res > 0:
            print("b = %d/%d is not an integer!" % (v * r, k))
            return False
    return True
# end def   

def show_admissible_BIBD(v, k, lamb):
    print("(%d, %d, %d) is admissible?" % (v, k, lamb), is_admissible_BIBD(v, k, lamb), "\n") 
# end def   

show_admissible_BIBD(15, 3, 2)
show_admissible_BIBD(8, 3, 1) # not admissible
show_admissible_BIBD(19, 4, 1) # not admissible
show_admissible_BIBD(22, 7, 2) # admissible but not exist
show_admissible_BIBD(43, 7, 1) # admissible but not exist

(15, 3, 2) is admissible? True 

r = 7/2 is not an integer!
(8, 3, 1) is admissible? False 

b = 114/4 is not an integer!
(19, 4, 1) is admissible? False 

(22, 7, 2) is admissible? True 

(43, 7, 1) is admissible? True 



## Example: Cyclic BIBD by developing the base blocks

In [8]:
def dev_base_block(v, base_blocks):
    block_li = []
    for b in base_blocks:
        block_li += [ sorted(list( (np.array(b) + i) % v)) for i in range(v) ]
    # remove duplicated blocks
    final_block_li = []
    for b in block_li:
        if b not in final_block_li:
            final_block_li.append(b)
    return final_block_li
# end def 

v = 7
base_blocks = [[0, 1, 3]] 
print("Cyclic (%d,3,1) BIBD: \n" % v, np.array(dev_base_block(v, base_blocks)), "\n")

v = 15
base_blocks = [[0,1,4], [0,2,8], [0,5,10]] 
print("Cyclic (%d,3,1) BIBD: \n" % v, np.array(dev_base_block(v, base_blocks)), "\n")


Cyclic (7,3,1) BIBD: 
 [[0 1 3]
 [1 2 4]
 [2 3 5]
 [3 4 6]
 [0 4 5]
 [1 5 6]
 [0 2 6]] 

Cyclic (15,3,1) BIBD: 
 [[ 0  1  4]
 [ 1  2  5]
 [ 2  3  6]
 [ 3  4  7]
 [ 4  5  8]
 [ 5  6  9]
 [ 6  7 10]
 [ 7  8 11]
 [ 8  9 12]
 [ 9 10 13]
 [10 11 14]
 [ 0 11 12]
 [ 1 12 13]
 [ 2 13 14]
 [ 0  3 14]
 [ 0  2  8]
 [ 1  3  9]
 [ 2  4 10]
 [ 3  5 11]
 [ 4  6 12]
 [ 5  7 13]
 [ 6  8 14]
 [ 0  7  9]
 [ 1  8 10]
 [ 2  9 11]
 [ 3 10 12]
 [ 4 11 13]
 [ 5 12 14]
 [ 0  6 13]
 [ 1  7 14]
 [ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 



## Example: Primitive root mod $p$

In [9]:
p = 13 # p is a prime
g = 2 # 2 is primitive mod 13
cyc_gp = [1]
ord_g = 0
for i in range(1, p+1):
    ele = cyc_gp[i-1] * g % p
    cyc_gp.append(ele)
    print("g^%d = %d" % (i, ele))
    if ele == 1:
        ord_g = i
        break;
print("g = %d is of order %d." % (g, ord_g))
if ord_g == p-1:
    print("Hence g = %d  is a primitive root mod %d." % (g, p) )


g^1 = 2
g^2 = 4
g^3 = 8
g^4 = 3
g^5 = 6
g^6 = 12
g^7 = 11
g^8 = 9
g^9 = 5
g^10 = 10
g^11 = 7
g^12 = 1
g = 2 is of order 12.
Hence g = 2  is a primitive root mod 13.


## Example: cyclotomic construction for STS$(13)$

In [10]:
v = 13
base_blocks = [[1,3,9], [2,6,5]] 
print("Cyclic (%d,3,1) BIBD: \n" % v, np.array(dev_base_block(v, base_blocks)), "\n")

Cyclic (13,3,1) BIBD: 
 [[ 1  3  9]
 [ 2  4 10]
 [ 3  5 11]
 [ 4  6 12]
 [ 0  5  7]
 [ 1  6  8]
 [ 2  7  9]
 [ 3  8 10]
 [ 4  9 11]
 [ 5 10 12]
 [ 0  6 11]
 [ 1  7 12]
 [ 0  2  8]
 [ 2  5  6]
 [ 3  6  7]
 [ 4  7  8]
 [ 5  8  9]
 [ 6  9 10]
 [ 7 10 11]
 [ 8 11 12]
 [ 0  9 12]
 [ 0  1 10]
 [ 1  2 11]
 [ 2  3 12]
 [ 0  3  4]
 [ 1  4  5]] 



## Example: HDP$(v)$ with $v = 18s+1$, $s \geq 2$

In [11]:
def reflect_triple(triple, v):
    new_triple=[]
    for x in triple:
        if x <= (v-1)/2:
            new_triple.append(x)
        else:
            new_triple.append(v-x)
    return new_triple
# end def

s = 2
v = 18 * s + 1
hdp = []
for r in range(s):
    hdp.append( reflect_triple([3*r + 1, 4*s-r+1, 4*s+2*r+2], v) )
for r in range(s):
    hdp.append( reflect_triple([3*r + 2, 8*s-r, 8*s+2*r+2], v) )
for r in range(s-1):
    hdp.append( reflect_triple([3*r + 3, 6*s-2*r-1, 6*s+r+2], v) )
hdp.append( [3*s, 3*s+1, 6*s+1] )

print("HDP(%d): \n" % v, np.array(hdp), "\n")

union_hdp = []
for triple in hdp:
    union_hdp += triple
print(sorted(union_hdp) )

HDP(37): 
 [[ 1  9 10]
 [ 4  8 12]
 [ 2 16 18]
 [ 5 15 17]
 [ 3 11 14]
 [ 6  7 13]] 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [12]:
from datetime import datetime
from pytz import timezone

lastest_time = datetime.now(timezone('Asia/Tokyo'))
print("Last updated at ", lastest_time.strftime('%Y-%m-%d %H:%M:%S'))

Last updated at  2021-08-26 12:54:15
