# Advanced Applied Math II (Intensive course in Kobe Univ., Aug. 2021)
### Instructor: Xiao-Nan Lu (Univ. Yamanashi)

# Day 4: Error-Correcting Codes

## Example: Encoding using $[7,4]$ Hamming code

In [1]:
import numpy as np

def generator_mat_Hamming():
    G = np.array([ [0, 1, 1, 1],  [1, 0, 1, 1], [1, 1, 0, 1] ]).transpose()
    G = np.append(np.eye(4), G, axis=1)
    print("Generator matrix = \n", G)
    return G
    
def encoding(msg, G):
    # msg should be a row vector of dim 4 for Hamming code
    return np.matmul(msg, G) % 2
    
def encoding_int(n, G):
    m = np.array(  [int(i) for i in '{0:06b}'.format(n)[2:]]  )
    return encoding(m, G)

G = generator_mat_Hamming()
print("All codewords: ")
for n in range(16):
    enc_m = encoding_int(n, G)
    print(enc_m) #"Codeword for %d = " % n, 
    

Generator matrix = 
 [[1. 0. 0. 0. 0. 1. 1.]
 [0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1. 1. 1.]]
All codewords: 
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 1. 1. 1.]
[0. 0. 1. 0. 1. 1. 0.]
[0. 0. 1. 1. 0. 0. 1.]
[0. 1. 0. 0. 1. 0. 1.]
[0. 1. 0. 1. 0. 1. 0.]
[0. 1. 1. 0. 0. 1. 1.]
[0. 1. 1. 1. 1. 0. 0.]
[1. 0. 0. 0. 0. 1. 1.]
[1. 0. 0. 1. 1. 0. 0.]
[1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 1. 0. 1. 0.]
[1. 1. 0. 0. 1. 1. 0.]
[1. 1. 0. 1. 0. 0. 1.]
[1. 1. 1. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


## Example: Syndrome decoding using $[7,4]$ Hamming code

In [2]:
def dec_Hamming(msg):
    # msg should be a row vector of dim 7
    msg = msg.reshape([1, 7])
    H = np.array([ [0, 1, 1, 1],  [1, 0, 1, 1], [1, 1, 0, 1] ]) 
    H = np.append(H, np.eye(3), axis=1)
    print("Parity check matrix = \n", H)
    syndrome = np.matmul(H, msg.transpose()) % 2
    print("Syndrome = \n", syndrome) 

    # error-correcting
    b = np.where(np.all(H[:, :] == syndrome, axis=0))
    if b[0].size == 0:
        print("No error")
        dec_msg = msg[0]
    else:
        print("Error at bit No.", b[0][0]+1)
        dec_msg  = np.array([ 1-msg[0][i] if i==b[0][0] else msg[0][i] for i in range(7) ])

    return dec_msg[0: 4]

m = np.array([1, 1, 0, 0, 1, 1 , 1])
dec_m = dec_Hamming(m)

print("Decoded message = ", dec_m) 
print("-> decimal number",  np.matmul([8,4,2,1], dec_m))

Parity check matrix = 
 [[0. 1. 1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1.]]
Syndrome = 
 [[0.]
 [0.]
 [1.]]
Error at bit No. 7
Decoded message =  [1 1 0 0]
-> decimal number 12


In [3]:
from datetime import datetime
from pytz import timezone

lastest_time = datetime.now(timezone('Asia/Tokyo'))
print("Last updated at ", lastest_time.strftime('%Y-%m-%d %H:%M:%S'))

Last updated at  2021-08-30 08:40:16
